import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { describe, it } from "node:test";

const expectedKeys = [
  "SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
  "CELO_RPC_URL",
  "CELO_MAINNET_RPC_URL",
  "CELO_MAINNET_RPC_FALLBACK_URL",
  "CELO_ATTRIBUTION_TAG",
  "CELO_SEPOLIA_RPC_URL",
  "BASE_RPC_URL",
  "EXECUTOR_PRIVATE_KEY",
  "SETUP_DEPLOYER_PRIVATE_KEY",
  "AGENTPAY_OWNER_ADDRESS",
  "AGENTPAY_EXECUTOR_ADDRESS",
  "AGENTPAY_HOME_CHAIN_ID",
  "AGENTPAY_CONSUMER_MCP_URL",
  "AGENTPAY_PAID_MCP_URL",
  "AGENTPAY_PUBLIC_SETUP_URL",
  "AGENTPAY_PUBLIC_REVIEW_URL",
  "AGENTPAY_HTTP_MODE",
  "AGENTPAY_ENVIRONMENT",
  "AGENTPAY_MAINNET_MANIFEST_PATH",
  "AGENTPAY_ONBOARDING_MANIFEST_PATH",
  "AGENTPAY_ONBOARDING_MANIFEST_SHA256",
  "AGENTPAY_ACCOUNT_RUNTIME_ARTIFACT_PATH",
  "AGENTPAY_FACTORY_ADDRESS",
  "AGENTPAY_FACTORY_RUNTIME_CODE_HASH",
  "AGENTPAY_SETUP_SPONSOR_ADDRESS",
  "AGENTPAY_SETUP_SUPABASE_PROJECT_REF",
  "AGENTPAY_SETUP_MODE",
  "AGENTPAY_SESSION_HASH_KEY",
  "AGENTPAY_REVIEW_TOKEN_SECRET",
  "AGENTPAY_RAW_TX_ENCRYPTION_KEY",
  "AGENTPAY_ACCOUNT_ADDRESS",
  "AGENTPAY_CELO_USDC_ADDRESS",
  "AGENTPAY_CELO_USDT_ADDRESS",
  "AGENTPAY_CELO_USDM_ADDRESS",
  "AGENTPAY_CELO_SEPOLIA_USDC_ADDRESS",
  "AGENTPAY_CELO_SEPOLIA_USDT_ADDRESS",
  "AGENTPAY_CELO_SEPOLIA_USDM_ADDRESS",
  "AGENTPAY_ACCOUNT_BYTECODE_PATH",
  "AGENTPAY_ACCOUNT_BYTECODE",
  "AGENTPAY_ACCOUNT_VERSION",
  "AGENTPAY_ACCOUNT_BYTECODE_HASH",
  "AGENTPAY_INITIAL_ROUTE_TARGETS",
  "SETUP_WEB_URL",
  "SETUP_WEB_PORT",
  "LIFI_API_KEY",
  "LIFI_BASE_URL",
  "X402_BAZAAR_FACILITATOR_URL",
  "AGENTPAY_A2MCP_PAYMENT_ENABLED",
  "AGENTPAY_A2MCP_PAYMENT_PAY_TO",
  "AGENTPAY_A2MCP_PAYMENT_PRICE",
  "AGENTPAY_A2MCP_PAYMENT_NETWORK",
  "AGENTPAY_A2MCP_PAYMENT_ASSET",
  "AGENTPAY_A2MCP_PAYMENT_MAX_TIMEOUT_SECONDS",
  "AGENTPAY_A2MCP_PAYMENT_ASSET_DECIMALS",
  "AGENTPAY_A2MCP_PAYMENT_SYNC_SETTLE",
  "AGENTPAY_A2MCP_PAYMENT_ASSET_TRANSFER_METHOD",
  "AGENTPAY_A2MCP_PAYMENT_FACILITATOR_URL",
  "AGENTPAY_CELO_X402_API_KEY",
];

function parseEnvExampleKeys(contents) {
  return contents
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"))
    .map((line) => line.split("=", 1)[0]);
}

describe(".env.example", () => {
  it("matches the AgentPay installer and runtime config keys", async () => {
    const contents = await readFile(".env.example", "utf8");
    const keys = parseEnvExampleKeys(contents);

    assert.deepEqual(keys, expectedKeys);
  });
});
